### ISSUE TITLE
Parsing DICOM files with dcmjs failes if data set is corrupted

### ISSUE THREAD

**Issue by kursawero** [ddRPB/rpb-uploader#64]

**Comment by kursawero** [comment]
It seems that we have problems if the GroupLength is wrong. I created a ticket https://github.com/dcmjs-org/dcmjs/issues/338 to ask for help.

**Comment by toskrip** [comment]
we may need to give anonymised example file as prerequisite for bug replication

**Comment by kursawero** [comment]
First, we will notify the user on early state that there are problems with specific files: #65

**Comment by kursawero** [comment]
Created a pull request for a fix [Pull Request](https://github.com/dcmjs-org/dcmjs/pull/346/files)

**Comment by kursawero** [comment]
Pull request is merged - problem is fixed
